site_name: ECE Common Course Tutorials
site_author: 'ECE Course Staff'

repo_name:   'cornell-ece-docs/ece-tutorials'

# Removes the ugly 'Edit on" buttons'
# repo_url:    'https://github.com/cornell-ece-docs/ece-tutorials'

# Copyright

copyright:   'Copyright &copy; 2024 Christopher Batten, ECE Course Staff'

# Theme

theme: flatly

markdown_extensions:
  - attr_list
  - sane_lists

nav:
  - Home: 'index.md'
  - Tutorials:
    - 'tut0-ecelinux.md'
    - 'tut1-linux-cli.md'
    - 'tut2-git.md'
  - Guides:
    - 'doc0-coding-style.md'
  - ECE2400:
    - 'sec1-gcc.md'
    - 'sec2-cmake.md'
    - 'sec3-debug.md'
    - 'sec7-sort.md'
    - 'sec8-cpp.md'
    - 'sec9-polymorphism.md'
    - 'sec10-monomorph.md'
